development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: webgeek
  pool: 10
  username: webgeek
  password: webgeek
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: webgeek
  pool: 10
  username: webgeek
  password: webgeek
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: webgeek
  pool: 10
  username: webgeek
  password: webgeek
